plugins {
    id "com.android.application"
    id "com.google.gms.google-services"
}

def runNumber = System.getenv("GITHUB_RUN_NUMBER") ?: "1"

android {
    namespace "br.com.templodagloriaeterna.app"
    compileSdk 35

    defaultConfig {
        applicationId "br.com.templodagloriaeterna.app"
        minSdk 23
        targetSdk 35
        versionCode runNumber.toInteger()
        versionName "1.0." + runNumber
        resValue "string", "launch_url", "https://www.templodagloriaeterna.com.br/membro/entrar?android_app_version=android-${runNumber}"
    }

    signingConfigs {
        release {
            storeFile file("release.jks")
            storePassword System.getenv("ANDROID_KEYSTORE_PASSWORD")
            keyAlias System.getenv("ANDROID_KEY_ALIAS")
            keyPassword System.getenv("ANDROID_KEY_PASSWORD")
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }
}

dependencies {
    implementation "androidx.core:core:1.15.0"
    implementation platform("com.google.firebase:firebase-bom:34.18.0")
    implementation "com.google.firebase:firebase-messaging"
}
